test: using config file to run daemon test
alibaba/pouch pull request #2950
Opened 2019-07-15 09:22 UTC by zhuangqh

*background*: some env may depend on some
specific config options.

Signed-off-by: zhuangqh <zhuangqhc@gmail.com>

### Ⅰ. Describe what this PR did

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? (你真的觉得不需要加测试吗？)

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2019-07-17 12:46 UTC, fuweid commented
@zhuangqh I trigger the CI to rerun it.

2019-07-17 13:36 UTC, fuweid commented
```
go test -c \
	-o bin/pouchd-integration-test github.com/alibaba/pouch/test
# github.com/alibaba/pouch/test [github.com/alibaba/pouch/test.test]
test/cli_logs_test.go:254:34: cannot use "--log-opt" (type string) as type map[string]interface {} in argument to StartDefaultDaemon
Makefile:215: recipe for target 'build-integration-test' failed
make: *** [build-integration-test] Error 2
The command "./travis_ci.sh integrationtest 4 0" exited with 2.
```

ping @zhuangqh

2019-10-26 13:27 UTC, fuweid commented
ping @zhuangqh any update?

2020-06-12 06:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/pouch?pullRequest=2950) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/pouch?pullRequest=2950) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/pouch?pullRequest=2950) it.</sub>

2022-07-11 04:12 UTC, cxz66666 requested changes

2022-07-11 04:12 UTC, cxz66666 commented on test/cli_logs_test.go
> +		"--log-opt": fmt.Sprintf("root-dir=%s", logRootDir),
This need use args instead of config field? Or use `log-opt` instead of `--log-opt`? I'm not sure 😢

2022-07-18 07:53 UTC, cxz66666 commented
Thank you for your contribution! because you don't response for a long time, I will close this PR and reopen https://github.com/alibaba/pouch/pull/3036.

2022-07-18 07:53 UTC, closed without merging